#!/bin/bash
sudo -S apt-get update
sudo -S apt-get install -y aptitude
sudo -S aptitude update
mkdir ~/gitclones
sudo -S aptitude install -y --with-recommends \

# package utilities
sudo -S aptitude install -y --with-recommends checkinstall pkg-config gdebi \


# helper utilities 
sudo -S aptitude install -y --with-recommends zip unzip \

# console stuff
sudo -S aptitude install -y --with-recommends vim tmux zsh mc picocom \

# version control
sudo -S aptitude install -y --with-recommends git mercurial subversion

# dev tools
sudo -S aptitude install -y --with-recommends autoconf automake make cmake build-essential doxygen ddd

# verification tools
sudo -S aptitude install -y --with-recommends valgrind cppcheck uncrustify astyle clang-format-3.7

# compilers and debuggers
sudo -S aptitude install -y --with-recommends gcc-arm-none-eabi gdb-arm-none-eabi clang libclang-dev 

# embedded tools, prerequisites for hidapi
sudo -S aptitude install -y --with-recommends libudev-dev libusb-dev libusb-1.0-0-dev libfox-1.6-dev

# stlink
cd ~/gitclones && git clone git://github.com/texane/stlink.git && cd stlink && ./autogen.sh && ./configure && make
sudo checkinstall -y --pkgversion=1 
sudo cp 49-stlinkv1.rules /etc/udev/rules.d && sudo cp 49-stlinkv2.rules /etc/udev/rules.d && sudo udevadm control --reload-rules
# openocd
cd ~/gitclones && git clone git://openocd.git.sourceforge.net/gitroot/openocd/openocd  && cd openocd && ./bootstrap && ./configure && make

# general purpose libraries
sudo -S aptitude install -y --with-recommends libboost-all-dev libpoco-dev 

# other libraries
sudo -S aptitude install -y --with-recommends libeigen3-dev libflann-dev libtbb-dev

# testing libraries
sudo -S aptitude install -y --with-recommends libgtest-dev libcunit1-dev libcppunit-dev 
#build gtest
sudo cd /usr/src/gtest && cmake CMakeLists.txt && make && cp *.a /usr/lib


# CI: Jenkins
wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
sudo aptitude update
sudo -S aptitude install -y --with-recommends jenkins

# Python environment - IDE, anaconda?
sudo -S aptitude install -y --with-recommends spyder

# environments and window managers
sudo -S aptitude install -y --with-recommends awesome 
sudo -S aptitude install -y --with-recommends wine
# xfce4 ?

# IDE 
# qt creator
sudo -S aptitude install -y --with-recommends qtcreator 
# eclipse
sudo -S aptitude install -y --with-recommends eclipse-cdt \
eclipse-cdt-autotools eclipse-cdt-jni eclipse-cdt-qt \
eclipse-cdt-perf eclipse-cdt-valgrind eclipse-cdt-pkg-config eclipse-cdt-profiling-framework \
eclipse-cdt-profiling-framework-remote eclipse-cdt-launch-remote 

# UnrealEngine
# Steps (summarised):
# 1. Download Unreal Engine 4 source code from their Github page
# 2. Extract it to desktop
# 3. Install dependencies via Terminal or USC
# 4. Open a Terminal and CD to the folder on the desktop
# 5. Run ./Setup.sh
# 6. Run ./GenerateProjectFiles.sh
# 7. Run make SlateViewer
# 8. Run make ShaderCompileWorker UnrealLightmass UnrealPak UE4Editor
# 9. Head into UnrealEngine/Engine/Binaries/Linux
# 10. Double click UE4Editor to run UE4!

#dependencies
sudo -S aptitude install -y --with-recommends mono-gmcs mono-xbuild mono-dmcs libmono-corlib4.0-cil libmono-system-data-datasetextensions4.0-cil \
libmono-system-web-extensions4.0-cil libmono-system-management4.0-cil libmono-system-xml-linq4.0-cil cmake dos2unix clang-3.5 xdg-user-dirs libqt4-dev
# TODO: remaining steps
#cd ~/gitclones && git clone https://github.com/EpicGames/UnrealEngine


# Applied Programs

# Math modeling, numerics
sudo -S aptitude install -y --with-recommends octave scilab 
# Statistics: R
sudo -S aptitude install -y --with-recommends r-base
# 3D Modelling
sudo -S aptitude install -y --with-recommends blender 
# CAD
sudo -S aptitude install -y --with-recommends freecad freecad-doc
# EDA (Electronic design automation )
#	gEDA
sudo -S aptitude install -y --with-recommends geda geda-utils geda-xgsch2pcb pcb 
# 	KiCAD
sudo -S aptitude install -y --with-recommends kicad kicad-doc-en
# PCB design
sudo -S aptitude install -y --with-recommends freepcb
# Electric circuit simulation
sudo -S aptitude install -y --with-recommends ngspice gnucap


# remote access
#openssh-server xrdp \


#install other: yandex disk, web browser, etc
sudo gdebi --n ~/distr/deb/yandex-scdisk_latest_amd65.deb 
sudo gdebi --n ~/distr/deb/google-chrome-stable_current_amd64.deb 

# Setup git (username, email, etc)
git config --global user.name "Nikolay Bobovnikov"
git config --global user.email "nbobovnikov@gmail.com"
git config --global credential.helper cache

